# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCT_cpp <- function(pval) {
    .Call('_SAIGE_CCT_cpp', PACKAGE = 'SAIGE', pval)
}

setGlobalVarsInCPP_LDmat <- function(t_impute_method, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_missing_cutoff, t_maxMAFLimit, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_max_markers_region, t_outputFile) {
    invisible(.Call('_SAIGE_setGlobalVarsInCPP_LDmat', PACKAGE = 'SAIGE', t_impute_method, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_missing_cutoff, t_maxMAFLimit, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_max_markers_region, t_outputFile))
}

LDmatRegionInCPP <- function(t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, t_outputFile, t_n, t_isImputation, annoStringVec, regionName) {
    invisible(.Call('_SAIGE_LDmatRegionInCPP', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, t_outputFile, t_n, t_isImputation, annoStringVec, regionName))
}

openOutfile_single_LDmat <- function(isappend) {
    .Call('_SAIGE_openOutfile_single_LDmat', PACKAGE = 'SAIGE', isappend)
}

closeOutfile_single_LDmat <- function() {
    invisible(.Call('_SAIGE_closeOutfile_single_LDmat', PACKAGE = 'SAIGE'))
}

set_dup_sample_index <- function(t_dup_sample_Index) {
    invisible(.Call('_SAIGE_set_dup_sample_index', PACKAGE = 'SAIGE', t_dup_sample_Index))
}

setAssocTest_GlobalVarsInCPP <- function(t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_weights_beta, t_outputFilePrefix, t_MACCutoffforER) {
    invisible(.Call('_SAIGE_setAssocTest_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_impute_method, t_missing_cutoff, t_min_maf_marker, t_min_mac_marker, t_min_info_marker, t_dosage_zerod_cutoff, t_dosage_zerod_MAC_cutoff, t_weights_beta, t_outputFilePrefix, t_MACCutoffforER))
}

setMarker_GlobalVarsInCPP <- function(t_isOutputMoreDetails, t_marker_chunksize) {
    invisible(.Call('_SAIGE_setMarker_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_isOutputMoreDetails, t_marker_chunksize))
}

setRegion_GlobalVarsInCPP <- function(t_max_maf_region, t_max_markers_region, t_MACCutoff_to_CollapseUltraRare, t_min_gourpmac_for_burdenonly) {
    invisible(.Call('_SAIGE_setRegion_GlobalVarsInCPP', PACKAGE = 'SAIGE', t_max_maf_region, t_max_markers_region, t_MACCutoff_to_CollapseUltraRare, t_min_gourpmac_for_burdenonly))
}

mainMarkerInCPP <- function(t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth) {
    invisible(.Call('_SAIGE_mainMarkerInCPP', PACKAGE = 'SAIGE', t_genoType, t_traitType, t_genoIndex_prev, t_genoIndex, t_isMoreOutput, t_isImputation, t_isFirth))
}

Unified_getSampleSizeinGeno <- function(t_genoType) {
    .Call('_SAIGE_Unified_getSampleSizeinGeno', PACKAGE = 'SAIGE', t_genoType)
}

Unified_getSampleSizeinAnalysis <- function(t_genoType) {
    .Call('_SAIGE_Unified_getSampleSizeinAnalysis', PACKAGE = 'SAIGE', t_genoType)
}

setPLINKobjInCPP <- function(t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setPLINKobjInCPP', PACKAGE = 'SAIGE', t_bimFile, t_famFile, t_bedFile, t_SampleInModel, t_AlleleOrder))
}

setBGENobjInCPP <- function(t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder) {
    invisible(.Call('_SAIGE_setBGENobjInCPP', PACKAGE = 'SAIGE', t_bgenFileName, t_bgenFileIndex, t_SampleInBgen, t_SampleInModel, t_AlleleOrder))
}

setVCFobjInCPP <- function(t_vcfFileName, t_vcfFileIndex, t_vcfField, t_SampleInModel) {
    invisible(.Call('_SAIGE_setVCFobjInCPP', PACKAGE = 'SAIGE', t_vcfFileName, t_vcfFileIndex, t_vcfField, t_SampleInModel))
}

setSAIGEobjInCPP <- function(t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_Sigma_iXXSigma_iX, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio_sparse, t_varRatio_null, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_isFastTest, t_pval_cutoff_for_fastTest, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex, t_is_Firth_beta, t_pCutoffforFirth, t_offset, t_resout) {
    invisible(.Call('_SAIGE_setSAIGEobjInCPP', PACKAGE = 'SAIGE', t_XVX, t_XXVX_inv, t_XV, t_XVX_inv_XV, t_Sigma_iXXSigma_iX, t_X, t_S_a, t_res, t_mu2, t_mu, t_varRatio_sparse, t_varRatio_null, t_cateVarRatioMinMACVecExclude, t_cateVarRatioMaxMACVecInclude, t_SPA_Cutoff, t_tauvec, t_traitType, t_y, t_impute_method, t_flagSparseGRM, t_isFastTest, t_pval_cutoff_for_fastTest, t_locationMat, t_valueVec, t_dimNum, t_isCondition, t_condition_genoIndex, t_is_Firth_beta, t_pCutoffforFirth, t_offset, t_resout))
}

setSparseSigmaInCPP <- function(r, t_locationMatinR, t_valueVecinR) {
    invisible(.Call('_SAIGE_setSparseSigmaInCPP', PACKAGE = 'SAIGE', r, t_locationMatinR, t_valueVecinR))
}

RegionSetUpConditional_binary_InCPP <- function(t_weight_cond) {
    .Call('_SAIGE_RegionSetUpConditional_binary_InCPP', PACKAGE = 'SAIGE', t_weight_cond)
}

mainRegionInCPP <- function(t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat, t_regionTestType, t_isImputation, t_weight, t_weight_cond, t_isSingleinGroupTest, t_isOutputMarkerList, annoStringVec, regionName, t_isFastTest, t_isMoreOutput) {
    .Call('_SAIGE_mainRegionInCPP', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, annoIndicatorMat, maxMAFVec, t_outputFile, t_traitType, t_n, P1Mat, P2Mat, t_regionTestType, t_isImputation, t_weight, t_weight_cond, t_isSingleinGroupTest, t_isOutputMarkerList, annoStringVec, regionName, t_isFastTest, t_isMoreOutput)
}

assign_conditionMarkers_factors <- function(t_genoType, t_genoIndex_prev, t_genoIndex, t_n, t_weight_cond) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors', PACKAGE = 'SAIGE', t_genoType, t_genoIndex_prev, t_genoIndex, t_n, t_weight_cond))
}

assign_conditionMarkers_factors_binary_region <- function(scalefactor_G2_cond) {
    invisible(.Call('_SAIGE_assign_conditionMarkers_factors_binary_region', PACKAGE = 'SAIGE', scalefactor_G2_cond))
}

set_iterator_inVcf <- function(variantList, chrom, beg_pd, end_pd) {
    invisible(.Call('_SAIGE_set_iterator_inVcf', PACKAGE = 'SAIGE', variantList, chrom, beg_pd, end_pd))
}

check_Vcf_end <- function() {
    .Call('_SAIGE_check_Vcf_end', PACKAGE = 'SAIGE')
}

move_forward_iterator_Vcf <- function(i) {
    invisible(.Call('_SAIGE_move_forward_iterator_Vcf', PACKAGE = 'SAIGE', i))
}

fast_logistf_fit <- function(x, y, weight, offset, firth, col_fit, init, maxit, maxstep, maxhs, lconv, gconv, xconv, isfirthconverge) {
    .Call('_SAIGE_fast_logistf_fit', PACKAGE = 'SAIGE', x, y, weight, offset, firth, col_fit, init, maxit, maxstep, maxhs, lconv, gconv, xconv, isfirthconverge)
}

closeGenoFile <- function(t_genoType) {
    invisible(.Call('_SAIGE_closeGenoFile', PACKAGE = 'SAIGE', t_genoType))
}

openOutfile <- function(t_traitType, isappend) {
    .Call('_SAIGE_openOutfile', PACKAGE = 'SAIGE', t_traitType, isappend)
}

openOutfile_singleinGroup <- function(t_traitType, t_isImputation, isappend, t_isMoreOutput) {
    .Call('_SAIGE_openOutfile_singleinGroup', PACKAGE = 'SAIGE', t_traitType, t_isImputation, isappend, t_isMoreOutput)
}

openOutfile_single <- function(t_traitType, t_isImputation, isappend, t_isMoreOutput) {
    .Call('_SAIGE_openOutfile_single', PACKAGE = 'SAIGE', t_traitType, t_isImputation, isappend, t_isMoreOutput)
}

set_flagSparseGRM_cur_SAIGE <- function(t_flagSparseGRM_cur) {
    invisible(.Call('_SAIGE_set_flagSparseGRM_cur_SAIGE', PACKAGE = 'SAIGE', t_flagSparseGRM_cur))
}

set_flagSparseGRM_cur_SAIGE_org <- function() {
    invisible(.Call('_SAIGE_set_flagSparseGRM_cur_SAIGE_org', PACKAGE = 'SAIGE'))
}

copy_singleInGroup <- function() {
    invisible(.Call('_SAIGE_copy_singleInGroup', PACKAGE = 'SAIGE'))
}

set_I_longl_mat <- function(t_Ilongmat, t_I_longl_vec) {
    invisible(.Call('_SAIGE_set_I_longl_mat', PACKAGE = 'SAIGE', t_Ilongmat, t_I_longl_vec))
}

set_T_longl_mat <- function(t_Tlongmat, t_T_longl_vec) {
    invisible(.Call('_SAIGE_set_T_longl_mat', PACKAGE = 'SAIGE', t_Tlongmat, t_T_longl_vec))
}

addNewKat <- function(t_Kmat) {
    invisible(.Call('_SAIGE_addNewKat', PACKAGE = 'SAIGE', t_Kmat))
}

getProdTauKmat <- function(tauVec) {
    .Call('_SAIGE_getProdTauKmat', PACKAGE = 'SAIGE', tauVec)
}

set_store_sigma <- function(isstoreSigma) {
    invisible(.Call('_SAIGE_set_store_sigma', PACKAGE = 'SAIGE', isstoreSigma))
}

set_num_Kmat <- function(t_num_Kmat) {
    invisible(.Call('_SAIGE_set_num_Kmat', PACKAGE = 'SAIGE', t_num_Kmat))
}

getMeanDiagofKmat_largeMem <- function() {
    .Call('_SAIGE_getMeanDiagofKmat_largeMem', PACKAGE = 'SAIGE')
}

get_numofV <- function() {
    .Call('_SAIGE_get_numofV', PACKAGE = 'SAIGE')
}

set_longlVar_vec <- function(longlVec) {
    invisible(.Call('_SAIGE_set_longlVar_vec', PACKAGE = 'SAIGE', longlVec))
}

set_covarianceidx_Mat <- function() {
    .Call('_SAIGE_set_covarianceidx_Mat', PACKAGE = 'SAIGE')
}

set_Vmat_vec_longlVar <- function() {
    invisible(.Call('_SAIGE_set_Vmat_vec_longlVar', PACKAGE = 'SAIGE'))
}

closeGenoFile_plink <- function() {
    invisible(.Call('_SAIGE_closeGenoFile_plink', PACKAGE = 'SAIGE'))
}

gettotalMarker <- function() {
    .Call('_SAIGE_gettotalMarker', PACKAGE = 'SAIGE')
}

getAlleleFreqVec <- function() {
    .Call('_SAIGE_getAlleleFreqVec', PACKAGE = 'SAIGE')
}

getMACVec <- function() {
    .Call('_SAIGE_getMACVec', PACKAGE = 'SAIGE')
}

getMACVec_forVarRatio <- function() {
    .Call('_SAIGE_getMACVec_forVarRatio', PACKAGE = 'SAIGE')
}

getIndexVec_forVarRatio <- function() {
    .Call('_SAIGE_getIndexVec_forVarRatio', PACKAGE = 'SAIGE')
}

getIsVarRatioGeno <- function() {
    .Call('_SAIGE_getIsVarRatioGeno', PACKAGE = 'SAIGE')
}

getSubMarkerIndex <- function() {
    .Call('_SAIGE_getSubMarkerIndex', PACKAGE = 'SAIGE')
}

getQCdMarkerIndex <- function() {
    .Call('_SAIGE_getQCdMarkerIndex', PACKAGE = 'SAIGE')
}

getSubMarkerNum <- function() {
    .Call('_SAIGE_getSubMarkerNum', PACKAGE = 'SAIGE')
}

getNnomissingOut <- function() {
    .Call('_SAIGE_getNnomissingOut', PACKAGE = 'SAIGE')
}

getMsub_MAFge_minMAFtoConstructGRM <- function() {
    .Call('_SAIGE_getMsub_MAFge_minMAFtoConstructGRM', PACKAGE = 'SAIGE')
}

getMsub_MAFge_minMAFtoConstructGRM_singleChr <- function() {
    .Call('_SAIGE_getMsub_MAFge_minMAFtoConstructGRM_singleChr', PACKAGE = 'SAIGE')
}

Get_MultiMarkersBySample_StdGeno_Mat <- function() {
    invisible(.Call('_SAIGE_Get_MultiMarkersBySample_StdGeno_Mat', PACKAGE = 'SAIGE'))
}

Get_MultiMarkersBySample_StdGeno <- function(markerIndexVec, stdGenoMultiMarkers) {
    invisible(.Call('_SAIGE_Get_MultiMarkersBySample_StdGeno', PACKAGE = 'SAIGE', markerIndexVec, stdGenoMultiMarkers))
}

parallelCrossProd <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd', PACKAGE = 'SAIGE', bVec)
}

innerProductFun <- function(x, y) {
    .Call('_SAIGE_innerProductFun', PACKAGE = 'SAIGE', x, y)
}

parallelCrossProd_full <- function(bVec, markerNum) {
    .Call('_SAIGE_parallelCrossProd_full', PACKAGE = 'SAIGE', bVec, markerNum)
}

parallelCrossProd_LOCO <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd_LOCO', PACKAGE = 'SAIGE', bVec)
}

setupSparseGRM <- function(r, locationMatinR, valueVecinR) {
    invisible(.Call('_SAIGE_setupSparseGRM', PACKAGE = 'SAIGE', r, locationMatinR, valueVecinR))
}

setupSparseGRM_new <- function(t_spGRM) {
    invisible(.Call('_SAIGE_setupSparseGRM_new', PACKAGE = 'SAIGE', t_spGRM))
}

getCrossprodMatAndKin <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin', PACKAGE = 'SAIGE', bVec)
}

getCrossprodMatAndKin_LOCO <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_LOCO', PACKAGE = 'SAIGE', bVec)
}

printComb <- function(N) {
    invisible(.Call('_SAIGE_printComb', PACKAGE = 'SAIGE', N))
}

findIndiceRelatedSample <- function() {
    invisible(.Call('_SAIGE_findIndiceRelatedSample', PACKAGE = 'SAIGE'))
}

parallelcalsparseGRM <- function(GRMvec) {
    invisible(.Call('_SAIGE_parallelcalsparseGRM', PACKAGE = 'SAIGE', GRMvec))
}

parallelsumTwoVec <- function(x) {
    invisible(.Call('_SAIGE_parallelsumTwoVec', PACKAGE = 'SAIGE', x))
}

setgeno <- function(bedfile, bimfile, famfile, subSampleInGeno, indicatorGenoSamplesWithPheno, memoryChunk, isDiagofKinSetAsOne) {
    invisible(.Call('_SAIGE_setgeno', PACKAGE = 'SAIGE', bedfile, bimfile, famfile, subSampleInGeno, indicatorGenoSamplesWithPheno, memoryChunk, isDiagofKinSetAsOne))
}

Get_OneSNP_Geno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_Geno_forVarRatio <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_Geno_forVarRatio', PACKAGE = 'SAIGE', SNPIdx)
}

Get_OneSNP_StdGeno <- function(SNPIdx) {
    .Call('_SAIGE_Get_OneSNP_StdGeno', PACKAGE = 'SAIGE', SNPIdx)
}

getDiagOfSigma_largeMem__multiV <- function(wVec, tauVec, LOCO) {
    .Call('_SAIGE_getDiagOfSigma_largeMem__multiV', PACKAGE = 'SAIGE', wVec, tauVec, LOCO)
}

getDiagOfSigma_multiV <- function(wVec, tauVec, LOCO) {
    .Call('_SAIGE_getDiagOfSigma_multiV', PACKAGE = 'SAIGE', wVec, tauVec, LOCO)
}

getCrossprod_largeMem_multiV <- function(bVec, wVec, tauVec, LOCO) {
    .Call('_SAIGE_getCrossprod_largeMem_multiV', PACKAGE = 'SAIGE', bVec, wVec, tauVec, LOCO)
}

getCrossprod_multiV <- function(bVec, wVec, tauVec, LOCO) {
    .Call('_SAIGE_getCrossprod_multiV', PACKAGE = 'SAIGE', bVec, wVec, tauVec, LOCO)
}

gen_sp_GRM <- function() {
    .Call('_SAIGE_gen_sp_GRM', PACKAGE = 'SAIGE')
}

gen_sp_Sigma_largeMem_multiV <- function(wVec, tauVec) {
    .Call('_SAIGE_gen_sp_Sigma_largeMem_multiV', PACKAGE = 'SAIGE', wVec, tauVec)
}

gen_sp_Sigma_multiV <- function(wVec, tauVec) {
    invisible(.Call('_SAIGE_gen_sp_Sigma_multiV', PACKAGE = 'SAIGE', wVec, tauVec))
}

setisUsePrecondM <- function(isUseSparseSigmaforPCG) {
    invisible(.Call('_SAIGE_setisUsePrecondM', PACKAGE = 'SAIGE', isUseSparseSigmaforPCG))
}

setisUseSparseSigmaforInitTau <- function(isUseSparseSigmaforInitTau0) {
    invisible(.Call('_SAIGE_setisUseSparseSigmaforInitTau', PACKAGE = 'SAIGE', isUseSparseSigmaforInitTau0))
}

setisUseSparseSigmaforNullModelFitting <- function(isUseSparseSigmaforModelFitting0) {
    invisible(.Call('_SAIGE_setisUseSparseSigmaforNullModelFitting', PACKAGE = 'SAIGE', isUseSparseSigmaforModelFitting0))
}

getPCG1ofSigmaAndVector_multiV <- function(wVec, tauVec, bVec, maxiterPCG, tolPCG, LOCO) {
    .Call('_SAIGE_getPCG1ofSigmaAndVector_multiV', PACKAGE = 'SAIGE', wVec, tauVec, bVec, maxiterPCG, tolPCG, LOCO)
}

set_seed <- function(seed) {
    invisible(.Call('_SAIGE_set_seed', PACKAGE = 'SAIGE', seed))
}

nb <- function(n) {
    .Call('_SAIGE_nb', PACKAGE = 'SAIGE', n)
}

setStartEndIndex <- function(startIndex, endIndex, chromIndex) {
    invisible(.Call('_SAIGE_setStartEndIndex', PACKAGE = 'SAIGE', startIndex, endIndex, chromIndex))
}

setStartEndIndexVec <- function(startIndex_vec, endIndex_vec) {
    invisible(.Call('_SAIGE_setStartEndIndexVec', PACKAGE = 'SAIGE', startIndex_vec, endIndex_vec))
}

calCV <- function(xVec) {
    .Call('_SAIGE_calCV', PACKAGE = 'SAIGE', xVec)
}

getSigma_X_multiV <- function(wVec, tauVec, Xmat, maxiterPCG, tolPCG, LOCO) {
    .Call('_SAIGE_getSigma_X_multiV', PACKAGE = 'SAIGE', wVec, tauVec, Xmat, maxiterPCG, tolPCG, LOCO)
}

getSigma_G_multiV <- function(wVec, tauVec, Gvec, maxiterPCG, tolPCG, LOCO) {
    .Call('_SAIGE_getSigma_G_multiV', PACKAGE = 'SAIGE', wVec, tauVec, Gvec, maxiterPCG, tolPCG, LOCO)
}

parallelCrossProd_usingSubMarker <- function(bVec) {
    .Call('_SAIGE_parallelCrossProd_usingSubMarker', PACKAGE = 'SAIGE', bVec)
}

getCrossprodMatAndKin_usingSubMarker <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_usingSubMarker', PACKAGE = 'SAIGE', bVec)
}

parallelInnerProduct <- function(x, y) {
    .Call('_SAIGE_parallelInnerProduct', PACKAGE = 'SAIGE', x, y)
}

calGRMValueforSamplePair <- function(sampleidsVec) {
    .Call('_SAIGE_calGRMValueforSamplePair', PACKAGE = 'SAIGE', sampleidsVec)
}

createSparseKin <- function(markerIndexVec, relatednessCutoff, wVec, tauVec) {
    .Call('_SAIGE_createSparseKin', PACKAGE = 'SAIGE', markerIndexVec, relatednessCutoff, wVec, tauVec)
}

getColfromStdGenoMultiMarkersMat <- function(a) {
    .Call('_SAIGE_getColfromStdGenoMultiMarkersMat', PACKAGE = 'SAIGE', a)
}

getNColStdGenoMultiMarkersMat <- function() {
    .Call('_SAIGE_getNColStdGenoMultiMarkersMat', PACKAGE = 'SAIGE')
}

getNRowStdGenoMultiMarkersMat <- function() {
    .Call('_SAIGE_getNRowStdGenoMultiMarkersMat', PACKAGE = 'SAIGE')
}

setSubMarkerIndex <- function(subMarkerIndexRandom) {
    invisible(.Call('_SAIGE_setSubMarkerIndex', PACKAGE = 'SAIGE', subMarkerIndexRandom))
}

setRelatednessCutoff <- function(a) {
    invisible(.Call('_SAIGE_setRelatednessCutoff', PACKAGE = 'SAIGE', a))
}

innerProduct <- function(x, y) {
    .Call('_SAIGE_innerProduct', PACKAGE = 'SAIGE', x, y)
}

refineKin <- function(relatednessCutoff) {
    .Call('_SAIGE_refineKin', PACKAGE = 'SAIGE', relatednessCutoff)
}

shortenList <- function(iMat, kinValueVecTemp, relatednessCutoff, wVec, tauVec) {
    .Call('_SAIGE_shortenList', PACKAGE = 'SAIGE', iMat, kinValueVecTemp, relatednessCutoff, wVec, tauVec)
}

testTime <- function(i, m_bVec) {
    .Call('_SAIGE_testTime', PACKAGE = 'SAIGE', i, m_bVec)
}

gen_sp_v2 <- function(a) {
    .Call('_SAIGE_gen_sp_v2', PACKAGE = 'SAIGE', a)
}

gen_spsolve_v2 <- function(a) {
    .Call('_SAIGE_gen_spsolve_v2', PACKAGE = 'SAIGE', a)
}

gen_spsolve_inR <- function(a, y) {
    .Call('_SAIGE_gen_spsolve_inR', PACKAGE = 'SAIGE', a, y)
}

get_DiagofKin <- function() {
    .Call('_SAIGE_get_DiagofKin', PACKAGE = 'SAIGE')
}

getstdgenoVectorScalorProduct <- function(jth, y, prodVec) {
    invisible(.Call('_SAIGE_getstdgenoVectorScalorProduct', PACKAGE = 'SAIGE', jth, y, prodVec))
}

sumPz <- function(Pbvec, Ubvec, mmchunksize) {
    invisible(.Call('_SAIGE_sumPz', PACKAGE = 'SAIGE', Pbvec, Ubvec, mmchunksize))
}

mmGetPb_MbyN <- function(cthchunk, mmchunksize, bvec, Pbvec, kinbvec) {
    invisible(.Call('_SAIGE_mmGetPb_MbyN', PACKAGE = 'SAIGE', cthchunk, mmchunksize, bvec, Pbvec, kinbvec))
}

mmGetPb_NbyM <- function(cthchunk, mmchunksize, bvec, Pbvec) {
    invisible(.Call('_SAIGE_mmGetPb_NbyM', PACKAGE = 'SAIGE', cthchunk, mmchunksize, bvec, Pbvec))
}

muliplyMailman <- function(bvec, Gbvec, kinbvec) {
    invisible(.Call('_SAIGE_muliplyMailman', PACKAGE = 'SAIGE', bvec, Gbvec, kinbvec))
}

muliplyMailman_NbyM <- function(bvec, tGbvec) {
    invisible(.Call('_SAIGE_muliplyMailman_NbyM', PACKAGE = 'SAIGE', bvec, tGbvec))
}

freqOverStd <- function(freqOverStdVec) {
    invisible(.Call('_SAIGE_freqOverStd', PACKAGE = 'SAIGE', freqOverStdVec))
}

getCrossprodMatAndKin_mailman <- function(bVec) {
    .Call('_SAIGE_getCrossprodMatAndKin_mailman', PACKAGE = 'SAIGE', bVec)
}

get_GRMdiagVec <- function() {
    .Call('_SAIGE_get_GRMdiagVec', PACKAGE = 'SAIGE')
}

setminMAFforGRM <- function(minMAFforGRM) {
    invisible(.Call('_SAIGE_setminMAFforGRM', PACKAGE = 'SAIGE', minMAFforGRM))
}

setmaxMissingRateforGRM <- function(maxMissingforGRM) {
    invisible(.Call('_SAIGE_setmaxMissingRateforGRM', PACKAGE = 'SAIGE', maxMissingforGRM))
}

set_Diagof_StdGeno_LOCO <- function() {
    invisible(.Call('_SAIGE_set_Diagof_StdGeno_LOCO', PACKAGE = 'SAIGE'))
}

setminMAC_VarianceRatio <- function(t_minMACVarRatio, t_maxMACVarRatio, t_isVarianceRatioinGeno) {
    invisible(.Call('_SAIGE_setminMAC_VarianceRatio', PACKAGE = 'SAIGE', t_minMACVarRatio, t_maxMACVarRatio, t_isVarianceRatioinGeno))
}

getCoefficients_multiV <- function(Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG, LOCO) {
    .Call('_SAIGE_getCoefficients_multiV', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, maxiterPCG, tolPCG, LOCO)
}

GetTrace_largeMem_multiV <- function(Sigma_iX, Xmat, wVec, tauVec, fixtauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO) {
    .Call('_SAIGE_GetTrace_largeMem_multiV', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, fixtauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO)
}

GetTrace_multiV <- function(Sigma_iX, Xmat, wVec, tauVec, fixtauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO) {
    .Call('_SAIGE_GetTrace_multiV', PACKAGE = 'SAIGE', Sigma_iX, Xmat, wVec, tauVec, fixtauVec, cov1, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO)
}

getAIScore_largeMem_multiV <- function(Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO) {
    .Call('_SAIGE_getAIScore_largeMem_multiV', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO)
}

getAIScore_multiV <- function(Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO) {
    .Call('_SAIGE_getAIScore_multiV', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, traceCVcutoff, LOCO)
}

fitglmmaiRPCG_multiV <- function(Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff, LOCO) {
    .Call('_SAIGE_fitglmmaiRPCG_multiV', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff, LOCO)
}

fitglmmaiRPCG_largeMem_multiV <- function(Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff, LOCO) {
    .Call('_SAIGE_fitglmmaiRPCG_largeMem_multiV', PACKAGE = 'SAIGE', Yvec, Xmat, wVec, tauVec, fixtauVec, Sigma_iY, Sigma_iX, cov, nrun, maxiterPCG, tolPCG, tol, traceCVcutoff, LOCO)
}

getMeanDiagofKmat <- function(LOCO) {
    .Call('_SAIGE_getMeanDiagofKmat', PACKAGE = 'SAIGE', LOCO)
}

SPA <- function(mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp, traitType, pval, isSPAConverge))
}

SPA_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge) {
    invisible(.Call('_SAIGE_SPA_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, traitType, pval, isSPAConverge))
}

Korg_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Binom <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Binom', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Binom <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Binom', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Binom <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Binom', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Binom <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_binary <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_binary', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Binom <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Binom <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Binom', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Binom <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Binom', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Binom <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Binom', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_binary_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_binary_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

Korg_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_Korg_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

K1_adj_Poi <- function(t1, mu, g, q) {
    .Call('_SAIGE_K1_adj_Poi', PACKAGE = 'SAIGE', t1, mu, g, q)
}

K2_Poi <- function(t1, mu, g) {
    .Call('_SAIGE_K2_Poi', PACKAGE = 'SAIGE', t1, mu, g)
}

getroot_K1_Poi <- function(init, mu, g, q, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_Poi', PACKAGE = 'SAIGE', init, mu, g, q, tol, maxiter)
}

Get_Saddle_Prob_Poi <- function(zeta, mu, g, q, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, logp)
}

SPA_survival <- function(mu, g, q, qinv, pval_noadj, tol, logp) {
    .Call('_SAIGE_SPA_survival', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, tol, logp)
}

Korg_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_Korg_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K1_adj_fast_Poi <- function(t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K1_adj_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

K2_fast_Poi <- function(t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma) {
    .Call('_SAIGE_K2_fast_Poi', PACKAGE = 'SAIGE', t1, mu, g, gNA, gNB, muNA, muNB, NAmu, NAsigma)
}

getroot_K1_fast_Poi <- function(init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter) {
    .Call('_SAIGE_getroot_K1_fast_Poi', PACKAGE = 'SAIGE', init, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol, maxiter)
}

Get_Saddle_Prob_fast_Poi <- function(zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp) {
    .Call('_SAIGE_Get_Saddle_Prob_fast_Poi', PACKAGE = 'SAIGE', zeta, mu, g, q, gNA, gNB, muNA, muNB, NAmu, NAsigma, logp)
}

SPA_survival_fast <- function(mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol) {
    .Call('_SAIGE_SPA_survival_fast', PACKAGE = 'SAIGE', mu, g, q, qinv, pval_noadj, logp, gNA, gNB, muNA, muNB, NAmu, NAsigma, tol)
}

sum_arma1 <- function(X) {
    .Call('_SAIGE_sum_arma1', PACKAGE = 'SAIGE', X)
}

add_logp <- function(p1, p2) {
    .Call('_SAIGE_add_logp', PACKAGE = 'SAIGE', p1, p2)
}

mult_sp_sp_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_sp_sp_to_sp', PACKAGE = 'SAIGE', a, b)
}

mult_sp_den_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_sp_den_to_sp', PACKAGE = 'SAIGE', a, b)
}

mult_den_sp_to_sp <- function(a, b) {
    .Call('_SAIGE_mult_den_sp_to_sp', PACKAGE = 'SAIGE', a, b)
}

gen_sp <- function(a) {
    .Call('_SAIGE_gen_sp', PACKAGE = 'SAIGE', a)
}

